name: Run Unicode Bidirectional Character Scan
on:  
  workflow_dispatch:
  push:    
    branches:      
     - '**'

jobs:   
  ed-fi-repository-scanner:    
    uses: stevenarnold-ed-fi/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
    with:
      config-file-path: ./.github/workflows/bidi-scanner/config.json