name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  reusable-job:
    uses: stevenarnold-ed-fi/ed-fi-actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-scanner/config.json
