name: Call a reusable workflow

on:
  workflow_dispatch:

jobs:
  # scanner-alliance:
  #   uses: ed-fi-alliance-oss/ed-fi-actions/.github/workflows/repository-scanner.yml@latest
  #   with:
  #     config-file-path: ./.github/workflows/bidi-scanner/config.json
  scanner-fork:
    uses: stevenarnold-ed-fi/Ed-Fi-Actions/.github/workflows/repository-scanner.yml@main
    with:
      config-file-path: ./.github/workflows/bidi-scanner/config.json
